### ISSUE TITLE
very bad performance

### ISSUE THREAD

**Issue by McMelonTV** [joshmarinacci/node-pureimage#195]
Why does it take 12 seconds to create a 384x384 image and then make the background black?

```js
const now = Date.now()

const canvas = PImage.make(384, 384)
const ctx = canvas.getContext('2d')
ctx.fillStyle = '#000000'
ctx.fillRect(0, 0, canvas.width, canvas.height)

console.log('testPrint, image genrated in ', Date.now() - now, 'ms') //testPrint, image genrated in  12381 ms
```

**OS:** Android (React Native)
**PureImage Version:** 0.4.13

**Comment by McMelonTV** [comment]
this might actually just be because of the react native js runtime + the actual device performance
I have tried it in pure NodeJS and I got ~900ms on my phone (ran through nodejs in termux) and ~100ms on my pc

**Comment by joshmarinacci** [comment]
That does seem very slow. If you leave out the draw rect does it still take such a long time?

**Comment by McMelonTV** [comment]
# Android Phone
Without fillRect: 1377ms
With fillRect: 12376ms

# Android Emulator
Without fillRect: 216ms
With fillRect: 1435ms

**Comment by joshmarinacci** [comment]
Wow. That still seems crazy slow without fillRect.   The fast case for fillRect is a nested loop like this:

https://github.com/joshmarinacci/node-pureimage/blob/c2fefece5f0e68dfa1c1664e0a448f3f8e92d1a0/src/context.ts#L290


I know that some runtimes don't optimize the for loops, so that might be the problem. Still, that seems unusually slow for such a small area.  If this is for mobile can't you use the built in Canvas element?

**Comment by joshmarinacci** [comment]
Please reopen if you can still recreate this bug.
