### ISSUE TITLE
draw text loading ttf font

### ISSUE THREAD

**Issue by mcanet** [joshmarinacci/node-pureimage#3]
I am trying text rendering in osx and it does not work for me. It render rect or other things but text does not emerge error to load font but it does not render anything.

**Comment by joshmarinacci** [comment]
Hi Mcanet.  Since pure image is 100% JS it does not use native fonts. You must provide your own and register them before drawing anything.  there is a test font and some example code in the tests directory. It shows how to register a font before drawing.

https://github.com/joshmarinacci/node-pureimage/blob/master/tests/text.js

Good luck!
