### ISSUE TITLE
TextAlign not setting

### ISSUE THREAD

**Issue by DigitalKrony** [joshmarinacci/node-pureimage#31]
I'd like to be able to center the text in the image, however, the `ctx.textAlign="center"` seems to be ignored. 

Image renders, everything seems as it should be, the only issue is with the alignment. 

Ideas?

**Comment by c3mb0** [comment]
I'm having the same problem along with `ctx.textBaseline = 'middle'`. Has there been any progress on the issue?

**Comment by mesropd** [comment]
@c3mb0 You can use this workaround, until this issue is fixed.

```javascript
let fontSize = 48;
ctx.font = `${fontSize}pt 'Arial'`;
let textSize = ctx.measureText(comment);
ctx.fillText(text, originX - textSize.width / 2,  originY + fontSize / 2);
```

**Comment by joshmarinacci** [comment]
we need to implement the spec as defined here
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text

If text align is set to left then the text is draw starting at the x and going towards the right

if text align is set to right then the text is moved to the left so that it's right edge matches the x

if text align is set to center then the text is moved to the left so that the center point of the run of text is at the specified x.

**Comment by joshmarinacci** [comment]
This should be implemented now.
