### ISSUE TITLE
Send images on the fly

### ISSUE THREAD

**Issue by slidenerd** [joshmarinacci/node-pureimage#8]
First of all awesome work on the 100% PURE image processing library. Hats off to that. I have a usecase where I need to generate images containing text and they cant be stored as there are gonna be 100/1000s of them. Is there a way I can generate an image and send it to the client as a url that the client can view. Basically talking about creating an image on the fly

**EDIT 1**
It seems a base 64 url would do the job. Can I convert a generated image to a base 64 url

Thank you for your help in advance

**Comment by omril1** [comment]
Base 64 would work for images, but it sometimes causes problems with larger ones.
I think what you are looking for is piping streams, and that's the same reason I came here too.

**Comment by joshmarinacci** [comment]
Yes, you can do this. You'll need to store them in memory as a buffer instead of saving them to disk. However, you'll still need to serve them to the browser regardless of how they are stored. Your options are to base 64 encode them as a data URL, or you can render them directly to the data stream, referenced by a unique id. ex:

```
<img src="http://theserver.com/render?format=png&text=foobar"/>
```

then your server does something like

```
in event handler for the /render URL route
  var ctx = img.getContext('2d');
  //draw stuff
  img.renderToStream(res);
```

**Comment by robertmain** [comment]
How does it fail? What error does it give?

**Comment by TheLogan** [comment]
Well, the output seems to be an order of magnitude larger than what I expect 
(https://pastebin.com/BRHzYvvN)
And when I try to use the datastring as an image I'm being told that "the image cannot be displayed because it contains errors", which is not a lot to go on.

What I'm trying to do is:
> datauri.format('.png', img.data);
And then use
> datauri.content
